project:
  type: website
  output-dir: docs

website:
  title: "Mansheej Paul"
  search: false
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: About
      # - href: pubs.qmd
      - href: _files/mansheej_paul_resume.pdf
        text: CV

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
