project:
  type: website
  output-dir: docs

website:
  title: "Mansheej Paul"
  search: false
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: pubs.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
